prepare:
  image_directory: 'data_first_draft'
  annotations_directory: 'annotattions-first-train-draft'
  train_proportion: 0.7
  validation_proportion: 0.2
  test_proportion: 0.1
  seed: 4224
  gamma: 0.35
  adjust_images_brightness_strategy: 'Dark'
  percentile: 25

train:
  image_size: 640
  epochs: 500
  batch_size: 16
  init_lr: 0.001
  patience: 50
  seed: 4224
  optimizer: 'Adam'
  directory_output: 'output'

test:
  directory_output: 'output'
