names:
  0: B
  1: D
  2: C
  3: A
  4: V
  5: J
  6: I
  7: E
  8: F
  9: H
  10: K
  11: L
  12: M
  13: N
  14: O
  15: P
  16: Q
  17: R
  18: S
  19: T
  20: U
  21: W
  22: X
  23: Y
  24: Z
  25: space
  26: G
  27: del
train: train
val: validation
