names:
  0: N
  1: E
  2: L
  3: C
  4: Q
  5: F
  6: O
  7: J
  8: A
  9: M
  10: B
  11: D
  12: G
  13: H
  14: I
  15: K
  16: W
  17: T
  18: X
  19: P
  20: R
  21: S
  22: U
  23: V
  24: Y
  25: Z
  26: del
  27: space
train: train
val: validation
